---
name: CI

on:
  workflow_dispatch:
  push: &trigger
    branches:
      - main
    paths-ignore:
      - ".release-please/**"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/release-please.yml"
      - ".github/workflows/publish.yml"
  pull_request: *trigger

jobs:
  tests-and-lint:
    if: >
      github.event_name != 'pull_request'
      || github.event.pull_request.draft == false
    permissions:
      id-token: write
      contents: read
    uses: kimzuni-labs/workflows/.github/workflows/bun-ci.yml@main
    with:
      build: true
      test: true
      test-script: "test:coverage"
      codecov-upload: true
      lint: true
